---
- name: remove yum packaged ffmpeg
  become: yes
  yum: name=ffmpeg state=absent

- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - autoconf
    - automake
    - cmake
    - freetype-devel
    - gcc
    - gcc-c++
    - git
    - libtool
    - make
    - mercurial
    - nasm
    - pkgconfig
    - zlib-devel
