---
# Ogg bitstream library. Required by libtheora and libvorbis.
- name: libogg | Unarchive
  unarchive:
    src: http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz
    dest: "{{ source_dir }}"
    copy: no

- name: Compile | libogg
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/libogg-1.3.2"
    creates: "{{ bin_dir }}/libogg-1.3.2"
  with_items:
    - ./configure --prefix={{ build_dir }} --disable-shared
    - make
    - make install
    - make distclean
