---
# H.264 video encoder
- name: GIT clone | libx264
  git: repo=git://git.videolan.org/x264
       dest={{ source_dir }}/x264
       accept_hostkey=yes
       depth=1

- name: Compile | libx264
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/x264"
    creates: "{{ bin_dir }}/x264"
  with_items:
    - PKG_CONFIG_PATH="{{build_dir}}/lib/pkgconfig" ./configure --prefix={{ build_dir }} --bindir={{ bin_dir }} --enable-static
    - make
    - make install
    - make distclean
