---
- name: Mercurial | libx265
  hg: repo=https://bitbucket.org/multicoreware/x265
      dest={{source_dir}}/x265

- name: Compile | libx265
  shell: "export PATH=/usr/local/bin/:$PATH && {{ item }}"
  args:
    chdir: "{{ source_dir }}/x265/build/linux"
    creates: "{{ bin_dir }}/x265"
  with_items:
    - cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="{{build_dir}}" -DENABLE_SHARED:bool=off ../../source
    - make
    - make install
