development:
  # base_resolver_path: /access-images/jp2s
  base_resolver_path: <%= File.join Rails.root, 'test/images' %>
  base_video_resolver_path: <%= File.join Rails.root, 'public/videos' %>
  fun: true
