---
- name: install unzip
  yum:
    pkg: unzip
    state: present

- name: download & unarchive Kakadu
  unarchive:
    src: http://kakadusoftware.com/wp-content/uploads/2014/06/KDU77_Demo_Apps_for_Linux-x86-64_150710.zip
    dest: /opt
    copy: no

- name: ensures /opt/kdu directory exists
  file: path=/opt/kdu state=directory

# Maybe there's a better way to make sure binaries are in the path and
# the libraries are findable.
- name: copy kakadu to /opt/kdu
  shell: cp /opt/KDU77_Demo_Apps_for_Linux-x86-64*/* /opt/kdu/.

- name: ensures /opt/kdu/* binaries accessible
  file:
    path: /opt/kdu
    mode: "u=rwX,g=rX,o=rX"
    recurse: yes

- name: /etc/ld.so.conf.d/kdu.conf
  template:
    src: kdu.conf.j2
    dest: /etc/ld.so.conf.d/kdu.conf
    mode: "u=rw,g=r,o=r"

- name: /etc/profile.d/kdu.sh
  template:
    src: kdu.sh.j2
    dest: /etc/profile.d/kdu.sh
    mode: "u=rw,g=r,o=r"

- name: /etc/profile.d/kdu_ld_library.sh
  template:
    src: kdu_ld_library.sh.j2
    dest: /etc/profile.d/kdu_ld_library.sh
    mode: "u=rw,g=r,o=r"
