#install_roles.yml

# from galaxy
- src: https://github.com/rvm/rvm1-ansible.git
  version: "v2.0.1"
  name: rvm_io.ruby

- src: https://github.com/geerlingguy/ansible-role-redis.git
  version: "1.5.1"
  name: geerlingguy.redis

# from github, overriding the name and specifying a specific tag
- src: https://github.com/NCSU-Libraries-Ansible-Roles/basic-setup.git
  version: "v1.1.0"
  name: basic-setup

- src: https://github.com/NCSU-Libraries-Ansible-Roles/dev-dummy-cert.git  
  version: "v1.1.0"
  name: dev-dummy-cert

- src: https://github.com/NCSU-Libraries-Ansible-Roles/dev-link-opt-rails.git
  version: "v1.1.0"
  name: dev-link-opt-rails

- src: https://github.com/NCSU-Libraries-Ansible-Roles/ffmpeg.git
  version: "v1.2.0"
  name: ffmpeg

- src: https://github.com/NCSU-Libraries-Ansible-Roles/jp2.git
  version: "v1.1.0"
  name: jp2

- src: https://github.com/NCSU-Libraries-Ansible-Roles/passenger-apache.git
  version: "v1.1.1"
  name: passenger-apache

- src: https://github.com/NCSU-Libraries-Ansible-Roles/rvm-setup.git
  version: "v1.1.0"
  name: rvm-setup
